### ISSUE TITLE
Open Windows

### ISSUE THREAD

**Issue by typesupply** [typesupply/workspaces#3]
There needs to be a way to open windows needed for a workspace that aren't currently open. This can be handled internally like the lookup heuristics. It will be harder for other extensions because there is a race condition:

1. Foo.roboFontExtension wants to register "Foo Window".
2. Foo.roboFontExtension is loaded at startup.
3. Workspaces.roboFontExtension is loaded at startup.

Foo will not be able to register the window opener because the Workspaces registry is not available yet.

**Comment by typesupply** [comment]
@typemytype do you have any ideas on how to handle a situation in which Extension B needs to tell Extension A something, but B may be initialized before A is initialized?

**Comment by typemytype** [comment]
and extension can have an optional `requirements.txt` file with a list of required extension names see https://robofont.com/documentation/reference/extensions/extension-file-spec/#requirements

those extension will be loaded first, if it didnt happen already

(this happens a lot with extension where DrawBot is needed...)
